version: "3.8"
services:
  server:
    build: ./server
    container_name: node_monthly_wrapped
    ports:
      - '4000:4000'
    volumes:
      - ./server:/app
      - /app/node_modules
  client:
    build: ./client
    container_name: react_monthly_wrapped
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
      - /app/node_modules
